# -*- coding: utf-8 -*-
"""model_resnet18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eL4IG9u4x0B0C5XaGCBkfIf6DHmZeNVf
"""



# model.py

import torch.nn as nn
import pretrainedmodels

def get_model(pretrained):
 if pretrained:
    model = pretrainedmodels.__dict__["resnet18"](
    pretrained='imagenet'
    )
 else:
    model = pretrainedmodels.__dict__["resnet18"](
    pretrained=None
    )
 # print the model here to know whats going on.
 model.last_linear = nn.Sequential(
    nn.BatchNorm1d(512),
    nn.Dropout(p=0.25),
    nn.Linear(in_features=512, out_features=2048),
    nn.ReLU(),
    nn.BatchNorm1d(2048, eps=1e-05, momentum=0.1),
    nn.Dropout(p=0.5),
    nn.Linear(in_features=2048, out_features=1),
 )
 return model

